services:
  web:
    image: nginx:latest
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost/"]
       interval: 30s
       timeout: 10s
       start_period: 5s
       retries: 3

  db:
    image: mariadb:latest
    environment:
      MARIADB_DATABASE: mydb
      MARIADB_ROOT_PASSWORD: changeme
    healthcheck:
       test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MARIADB_ROOT_PASSWORD"]
       interval: 30s
       timeout: 10s
       start_period: 5s
       retries: 3
