services:
  web:
    image: nginx:latest
    healthcheck:
       test: ["CMD", "curl", "-f", "http://localhost/"]
       interval: 30s
       timeout: 10s
       start_period: 5s
       retries: 3

  db:
    image: mariadb:latest
    env_file:
      - cow.secrets.enc.env
