services:
  app:
    container_name: doco-cd
    image: ghcr.io/kimdre/doco-cd:latest
    restart: unless-stopped
#    ports:
#      - "80:80" # Webhook endpoint
#      - "9120:9120" # Prometheus metrics
    # For all available environment variables and explanations, see https://doco.cd/latest/App-Settings/
    environment:
      TZ: Europe/Berlin
      #GIT_ACCESS_TOKEN: xxx
      # WEBHOOK_SECRET: xxx  # Uncomment this line and the webhook port above and set a secure secret if you want to use webhooks.
      SOPS_AGE_KEY_FILE: /run/secrets/sops_age_key_file
      POLL_CONFIG: |
        - url: https://github.com/zahdr/doco-cd-test-app.git
          reference: main
          interval: 30
          target: ""
    secrets:
      - sops_age_key_file
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # The data volume (left side) can also be replaced with a bind mount to a local directory, for example:
      # - ./data:/data
      - data:/data
    cap_drop:
      - ALL
    healthcheck:
      test: [ "CMD", "/doco-cd", "healthcheck" ]
      start_period: 15s
      interval: 30s
      timeout: 5s
      retries: 3

volumes:
  data:

secrets:
  sops_age_key_file:
    file: sops_age_key.txt
